apiVersion: apps/v1
kind: Deployment
metadata:
  name: ewm-deployment
spec:
  selector:
    matchLabels:
      app: ewm-deployment
  replicas: 1 
  template:
    metadata:
      labels:
        app: ewm-deployment
    spec:
      containers:
      - name: ewm-image-sebastian3
        image: gcr.io/sap-asimov-ogoetz/ewm-image-sebastian:tag1
        env:
        - name: ODATA_USER
          value: "root"
        - name: ODATA_PASSWD
          value: "123"
        ports:
        - containerPort: 80